FROM ubuntu:24.04 AS prep_brew
ENV NONINTERACTIVE=1 HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_SANDBOX_LINUX=1
RUN --mount=type=cache,target=/var/lib/apt/lists,sharing=locked --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/root/.cache,sharing=locked echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/docker-clean && apt update && apt install -y curl git && { git clone --mirror https://github.com/Homebrew/brew /root/.cache/homebrew-git; git config --global url."file:///root/.cache/homebrew-git".insteadOf "https://github.com/Homebrew/brew"; } && touch /.dockerenv && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && for i in 1 2 3 4 5; do /home/linuxbrew/.linuxbrew/bin/brew install curl git glibc gcc && { echo "[Attempt $i] Success" && success=1 && break; } || { echo "[Attempt $i] Failed" && success=0 && sleep 1; }; done && if [ $success = 1 ]; then /home/linuxbrew/.linuxbrew/bin/brew cleanup --prune-prefix && rm -rf /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby && mv /home/linuxbrew/.linuxbrew/Homebrew/.git/index /root/.cache/homebrew_index; else exit 1; fi

FROM ubuntu:24.04 AS brewed
COPY --from=prep_brew /home/linuxbrew/.linuxbrew /home/linuxbrew/.linuxbrew
ENV HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_SANDBOX_LINUX=1 HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_CURL_PATH=/home/linuxbrew/.linuxbrew/bin/curl HOMEBREW_GIT_PATH=/home/linuxbrew/.linuxbrew/bin/git
RUN --mount=type=cache,target=/root/.cache,sharing=locked cp /root/.cache/homebrew_index /home/linuxbrew/.linuxbrew/Homebrew/.git/index && touch /.dockerenv && for i in 1 2 3 4 5; do /home/linuxbrew/.linuxbrew/bin/brew install gdb universal-ctags bash-completion@2 less file-formula unzip zsh gh vim zellij texinfo man-db yazi ffmpeg-full sevenzip jq poppler fd ripgrep fzf zoxide resvg imagemagick-full tlrc wl-clipboard bat eza starship lazygit hunk fastfetch hyperfine bun uv rustup go ruby lua luarocks zig sbcl clojure elixir r php swift duckdb forgecode && { echo "[Attempt $i] Success" && success=1 && break; } || { echo "[Attempt $i] Failed" && success=0 && sleep 1; }; done && if [ $success = 1 ]; then /home/linuxbrew/.linuxbrew/bin/brew cleanup --prune-prefix && rm -rf /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby; else exit 1; fi

FROM brewed
ENV EDITOR=vim SHELL=/home/linuxbrew/.linuxbrew/bin/zsh ZSH=/opt/oh-my-zsh ZSH_THEME= SSL_CERT_FILE=/home/linuxbrew/.linuxbrew/opt/ca-certificates/share/ca-certificates/cacert.pem LANG=en_US.utf8 LC_ALL=en_US.utf8 TERM=xterm-256color COLORTERM=truecolor LIBRARY_PATH="/home/linuxbrew/.linuxbrew/opt/glibc/lib" SDKROOT="/home/linuxbrew/.linuxbrew/opt/glibc" LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/glibc/lib" CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/glibc/include" XDG_DATA_HOME="/home/linuxbrew/.linuxbrew/share" XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:/root/.local/share:/usr/local/share:/usr/share" FORGE_TERM_MAX_COMMANDS=20 ZSH_BASH_COMPLETIONS_FALLBACK_PATH="/home/linuxbrew/.linuxbrew/opt/rustup/etc/bash_completion.d:/home/linuxbrew/.linuxbrew/etc/bash_completion.d" ZSH_BASH_COMPLETIONS_FALLBACK_LAZYLOAD_AUTO_UPDATE=1
RUN --mount=type=cache,target=/root/.cache,sharing=locked ln -s /home/linuxbrew/.linuxbrew/bin/bun /home/linuxbrew/.linuxbrew/bin/node && I18NPATH=/home/linuxbrew/.linuxbrew/opt/glibc/share/i18n /home/linuxbrew/.linuxbrew/opt/glibc/bin/localedef -i en_US -f UTF-8 /usr/lib/locale/en_US.utf8 && /home/linuxbrew/.linuxbrew/opt/glibc/bin/localedef --add-to-archive --replace /usr/lib/locale/en_US.utf8 && export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" && { git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git /root/.cache/oh-my-zsh; cp -r /root/.cache/oh-my-zsh $ZSH; } && { git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git /root/.cache/zsh-autosuggestions; cp -r /root/.cache/zsh-autosuggestions $ZSH/custom/plugins/zsh-autosuggestions; } && { git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git /root/.cache/zsh-syntax-highlighting; cp -r /root/.cache/zsh-syntax-highlighting $ZSH/custom/plugins/zsh-syntax-highlighting; } && { git clone --depth=1 https://github.com/opposj/zsh-bash-completions-fallback.git /root/.cache/zsh-bash-completions-fallback; cp -r /root/.cache/zsh-bash-completions-fallback $ZSH/custom/plugins/zsh-bash-completions-fallback; } && if [ ! -d /root/.cache/.quicklisp ]; then curl -o /root/.cache/ql.lisp http://beta.quicklisp.org/quicklisp.lisp && sbcl --load /root/.cache/ql.lisp --eval '(quicklisp-quickstart:install :path "/root/.cache/.quicklisp")' --quit; fi && cp -r /root/.cache/.quicklisp /root/.quicklisp && rm -rf /root/.quicklisp/tmp && sbcl --load /root/.quicklisp/setup.lisp --eval '(ql-util:without-prompting (ql:add-to-init-file))' --quit && if [ ! -f /root/.cache/alire.zip ]; then curl -Lo /root/.cache/alire.zip $(curl -s https://api.github.com/repos/alire-project/alire/releases/latest | rg '"browser_download_url": "(.*x86_64-linux.zip)"' -or '$1'); fi && unzip /root/.cache/alire.zip 'bin/alr' -d /home/linuxbrew/.linuxbrew && echo 'XTerm*metaSendsEscape: true' >> /root/.Xresources && ya pkg add yazi-rs/plugins:full-border && echo 'require("full-border"):setup()' >> /root/.config/yazi/init.lua && ya pkg add dangooddd/kanagawa && printf '%b\n' '[flavor]\ndark = "kanagawa"' >> /root/.config/yazi/theme.toml
COPY .zshenv .zshrc .vimrc /root/
ENTRYPOINT ["/home/linuxbrew/.linuxbrew/bin/zsh"]
